services:
  yfs-webui:
    image: rjyspl/yfs-webui:latest
    container_name: yfs-webui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3000:3000'
    restart: always
