blank_issues_enabled: true
contact_links:
  - name: 💬 Discord Community
    url: https://discord.gg/29zTxvque
    about: Chat with maintainers and other contributors, ask questions, and get help faster.
